[[constraint]]
  branch = "v2"
  name = "gopkg.in/yaml.v2"

[[constraint]]
  name = "github.com/asaskevich/govalidator"
  version = "8.0.0"

[[constraint]]
  name = "github.com/sirupsen/logrus"
  version = "1.0.4"
